table dim_date
	lineageTag: 689af88e-f6f9-408c-9654-069427ba55df
	dataCategory: Time

	column date_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c5ee54c9-9663-4dc4-8ff4-ea1640614473
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 729af0f1-44e4-49ca-a140-a07dc19f086f
		dataCategory: Time
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: fc55a254-3386-402b-bcea-c50fc7181c7f
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter_no
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 08ee951a-93e5-4549-951f-9ac4839c043f
		summarizeBy: none
		sourceColumn: quarter_no

		annotation SummarizationSetBy = Automatic

	column quarter_label
		dataType: string
		lineageTag: 36d845d7-a96d-4cfe-ae5e-70f055ba28fa
		summarizeBy: none
		sourceColumn: quarter_label
		sortByColumn: quarter_no

		annotation SummarizationSetBy = Automatic

	column year_quarter
		dataType: string
		lineageTag: 53ae787d-3e82-48ef-ae6a-e5573e09ae52
		summarizeBy: none
		sourceColumn: year_quarter

		annotation SummarizationSetBy = Automatic

	column month_no
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1fbfc1e5-be57-450c-95e9-b62f610367d5
		summarizeBy: none
		sourceColumn: month_no

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: b72109d0-0eb7-4427-98e5-affd4227b7dc
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 552e4bce-36ea-48a1-b511-ada04c8b92fa
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month_no

		annotation SummarizationSetBy = Automatic

	column month_name_short
		dataType: string
		lineageTag: 8b8f6575-32b1-4f37-b083-22766d60cfb7
		summarizeBy: none
		sourceColumn: month_name_short
		sortByColumn: month_no

		annotation SummarizationSetBy = Automatic

	column iso_week
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 81cb3062-9d15-4365-b4df-491d023e9e78
		summarizeBy: none
		sourceColumn: iso_week

		annotation SummarizationSetBy = Automatic

	column year_week
		dataType: string
		lineageTag: 6bd53fb1-08ce-4a84-8eb4-c68a9432f11d
		summarizeBy: none
		sourceColumn: year_week

		annotation SummarizationSetBy = Automatic

	column day_of_month
		dataType: int64
		formatString: 0
		lineageTag: c049d2e9-b92d-4856-bcee-593c8e454378
		summarizeBy: none
		sourceColumn: day_of_month

		annotation SummarizationSetBy = Automatic

	column day_of_year
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 651e1067-44dd-477f-b89e-5db3af055ffc
		summarizeBy: none
		sourceColumn: day_of_year

		annotation SummarizationSetBy = Automatic

	column day_of_week_no
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e2a3b3cf-7fc9-48c9-8868-23d9809149b6
		summarizeBy: none
		sourceColumn: day_of_week_no

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: 730270ae-e602-4acd-9019-70619e611b27
		summarizeBy: none
		sourceColumn: day_name
		sortByColumn: day_of_week_no

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		lineageTag: 88168b60-c2a2-479d-aa00-304f31e4fd6e
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_today
		dataType: boolean
		lineageTag: 0b7c9f16-0f1e-4acf-af9c-b028ea37e9b1
		summarizeBy: none
		sourceColumn: is_today

		annotation SummarizationSetBy = Automatic

	column is_current_month
		dataType: boolean
		lineageTag: aae8c15a-d3a3-424c-b02a-a344a7dc9f42
		summarizeBy: none
		sourceColumn: is_current_month

		annotation SummarizationSetBy = Automatic

	column is_current_year
		dataType: boolean
		lineageTag: 18cfb207-f421-4015-9167-022c7b5f0247
		summarizeBy: none
		sourceColumn: is_current_year

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(RepoPath & "/dim_date.csv"), [Delimiter=",", Columns=20, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"date_key", Int64.Type}, {"date", type date}, {"year", Int64.Type}, {"quarter_no", Int64.Type}, {"quarter_label", type text}, {"year_quarter", type text}, {"month_no", Int64.Type}, {"year_month", type text}, {"month_name", type text}, {"month_name_short", type text}, {"iso_week", Int64.Type}, {"year_week", type text}, {"day_of_month", Int64.Type}, {"day_of_year", Int64.Type}, {"day_of_week_no", Int64.Type}, {"day_name", type text}, {"is_weekend", type logical}, {"is_today", type logical}, {"is_current_month", type logical}, {"is_current_year", type logical}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table

