#!/usr/bin/env python3
"""
build_pbip.py
=============

Bygger en komplett Power BI PBIP-prosjektmappe fra de dimensjonale martene
i `models/marts/core/`. Datakilden er CSV-filer i `powerbi/data/` som blir
eksportert fra dbt + DuckDB.

Kjør:
    cd <repo-root>
    python powerbi/build_pbip.py

Output:
    powerbi/SalesAnalytics.pbip          ← åpne denne i Power BI Desktop
    powerbi/SalesAnalytics.Dataset/      ← semantisk modell (TMDL)
    powerbi/SalesAnalytics.Report/       ← rapport (JSON)

Struktur:
    * 5 tabeller — dim_customer, dim_product, dim_date, fct_orders, fct_order_items
    * 6 relasjoner — star schema
    * ~30 DAX-mål organisert i display-mapper
    * 6 rapportsider — Executive, Sales, Customers, Products, Trends, Dokumentasjon

Generated by Claude (Anthropic) for the Gritera Advisory GenAI workshop.
"""
import json
import os
import shutil
import uuid
import binascii


# ────────────────────────────────────────────────────────────────────────────
# Konstanter
# ────────────────────────────────────────────────────────────────────────────
PROJECT_NAME = "SalesAnalytics"
THIS_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = THIS_DIR                                    # powerbi/
DATASET_DIR = os.path.join(ROOT, f"{PROJECT_NAME}.SemanticModel")
REPORT_DIR = os.path.join(ROOT, f"{PROJECT_NAME}.Report")

# Visuelle dimensjoner (1920 × 1080-canvas)
CANVAS_W = 1920
CANVAS_H = 1080

# Gritera-fargepalett (rolig mørk-blå/teal som matcher Gritera Advisory)
BRAND_NAVY = "#0B2A4A"
BRAND_TEAL = "#1F8FA3"
BRAND_GOLD = "#E0A458"
BRAND_GREY = "#5B6770"
BRAND_BG   = "#F5F7FA"
WHITE      = "#FFFFFF"

# Standard CSV-mappe (relativ til repo-rot — settes som M-parameter)
DEFAULT_CSV_FOLDER = "data"

# Tracks all visuals we wrote in this build (per page) so we can neutralise
# stale random-named visual folders left over from previous builds. Necessary
# because the workshop folder is a mounted FS that allows OVERWRITE but not DELETE.
BUILT_VISUALS = {}

# Counters for deterministic visual folder names — `page_name → next_index`
_VISUAL_COUNTERS = {}
_CURRENT_PAGE = [None]


def set_current_page(page_name):
    """Called by write_page so subsequent gid() calls use page-scoped counters."""
    _CURRENT_PAGE[0] = page_name
    _VISUAL_COUNTERS.setdefault(page_name, 0)


# ────────────────────────────────────────────────────────────────────────────
# Hjelpefunksjoner
# ────────────────────────────────────────────────────────────────────────────
def gid():
    """
    Deterministisk 20-tegns id basert på (page, counter).
    Sikrer at gjenoppbygging skriver over samme filer — viktig på mounted
    filsystemer der vi ikke kan slette.
    """
    page = _CURRENT_PAGE[0] or "global"
    n = _VISUAL_COUNTERS.get(page, 0)
    _VISUAL_COUNTERS[page] = n + 1
    # 20-char hex name, encodes page+index deterministically
    import hashlib
    h = hashlib.md5(f"{page}::v{n:04d}".encode()).hexdigest()
    return h[:20]


def lineage_guid():
    """Generer en UUID-formatert lineage-tag (brukes av TMDL)."""
    return str(uuid.uuid4())


def write_json(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def write_text(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


# ────────────────────────────────────────────────────────────────────────────
# Tabellskjema (kolonner per tabell)
#   (column_name, data_type, summarize_by, format_string|None, sort_by|None)
# data_type: int64 | double | string | dateTime | boolean
# ────────────────────────────────────────────────────────────────────────────

TABLES = {
    "dim_customer": {
        "is_hidden": False,
        "data_category": None,
        "columns": [
            ("customer_sk",          "string",   "none",  None),
            ("customer_id",          "int64",    "none",  "0"),
            ("first_name",           "string",   "none",  None),
            ("last_name",            "string",   "none",  None),
            ("full_name",            "string",   "none",  None),
            ("email",                "string",   "none",  None),
            ("region",               "string",   "none",  None),
            ("customer_since_date",  "dateTime", "none",  "yyyy-mm-dd"),
            ("acquisition_month",    "dateTime", "none",  "yyyy-mm-dd"),
            ("acquisition_cohort",   "string",   "none",  None),
            ("acquisition_year",     "int64",    "none",  "0"),
            ("is_active",            "boolean",  "none",  None),
            ("customer_status",      "string",   "none",  None),
            ("tenure_segment",       "string",   "none",  None),
        ],
        "hidden_columns": {"customer_sk", "first_name", "last_name", "acquisition_month"},
    },

    "dim_product": {
        "is_hidden": False,
        "columns": [
            ("product_sk",            "string",   "none",   None),
            ("product_id",            "int64",    "none",   "0"),
            ("product_name",          "string",   "none",   None),
            ("category",              "string",   "none",   None),
            ("supplier",              "string",   "none",   None),
            ("list_price_nok",        "double",   "sum",    "#,##0.00 \"kr\""),
            ("standard_cost_nok",     "double",   "sum",    "#,##0.00 \"kr\""),
            ("list_margin_nok",       "double",   "sum",    "#,##0.00 \"kr\""),
            ("list_margin_pct",       "double",   "average","0.0%"),
            ("price_tier",            "string",   "none",   None),
            ("is_available",          "boolean",  "none",   None),
            ("availability_status",   "string",   "none",   None),
            ("product_launch_date",   "dateTime", "none",   "yyyy-mm-dd"),
            ("launch_year",           "int64",    "none",   "0"),
        ],
        "hidden_columns": {"product_sk"},
    },

    "dim_date": {
        "is_hidden": False,
        "data_category": "Time",
        "columns": [
            ("date_key",          "int64",    "none", "0"),
            ("date",              "dateTime", "none", "yyyy-mm-dd"),
            ("year",              "int64",    "none", "0"),
            ("quarter_no",        "int64",    "none", "0"),
            ("quarter_label",     "string",   "none", None),
            ("year_quarter",      "string",   "none", None),
            ("month_no",          "int64",    "none", "0"),
            ("year_month",        "string",   "none", None),
            ("month_name",        "string",   "none", None),
            ("month_name_short",  "string",   "none", None),
            ("iso_week",          "int64",    "none", "0"),
            ("year_week",         "string",   "none", None),
            ("day_of_month",      "int64",    "none", "0"),
            ("day_of_year",       "int64",    "none", "0"),
            ("day_of_week_no",    "int64",    "none", "0"),
            ("day_name",          "string",   "none", None),
            ("is_weekend",        "boolean",  "none", None),
            ("is_today",          "boolean",  "none", None),
            ("is_current_month",  "boolean",  "none", None),
            ("is_current_year",   "boolean",  "none", None),
        ],
        "hidden_columns": {"date_key", "quarter_no", "month_no", "day_of_week_no",
                           "day_of_year", "iso_week"},
        "sort_columns": {
            "month_name": "month_no",
            "month_name_short": "month_no",
            "day_name": "day_of_week_no",
            "quarter_label": "quarter_no",
        },
        "is_date_table": True,
    },

    "fct_orders": {
        "is_hidden": False,
        "columns": [
            ("order_id",          "int64",    "none", "0"),
            ("customer_sk",       "string",   "none", None),
            ("customer_id",       "int64",    "none", "0"),
            ("order_date_key",    "int64",    "none", "0"),
            ("order_date",        "dateTime", "none", "yyyy-mm-dd"),
            ("order_status",      "string",   "none", None),
            ("order_status_no",   "string",   "none", None),
            ("is_completed",      "boolean",  "none", None),
            ("is_returned",       "boolean",  "none", None),
            ("order_total_nok",   "double",   "sum",  "#,##0.00 \"kr\""),
            ("line_revenue_nok",  "double",   "sum",  "#,##0.00 \"kr\""),
            ("line_cost_nok",     "double",   "sum",  "#,##0.00 \"kr\""),
            ("line_profit_nok",   "double",   "sum",  "#,##0.00 \"kr\""),
            ("line_quantity",     "int64",    "sum",  "#,##0"),
            ("line_count",        "int64",    "sum",  "#,##0"),
        ],
        "hidden_columns": {"customer_sk", "order_date_key", "customer_id", "order_status"},
    },

    "fct_order_items": {
        "is_hidden": False,
        "columns": [
            ("order_item_id",     "int64",    "none", "0"),
            ("order_id",          "int64",    "none", "0"),
            ("customer_sk",       "string",   "none", None),
            ("customer_id",       "int64",    "none", "0"),
            ("product_sk",        "string",   "none", None),
            ("product_id",        "int64",    "none", "0"),
            ("order_date_key",    "int64",    "none", "0"),
            ("order_date",        "dateTime", "none", "yyyy-mm-dd"),
            ("order_status",      "string",   "none", None),
            ("is_completed",      "boolean",  "none", None),
            ("quantity",          "int64",    "sum",  "#,##0"),
            ("unit_price_nok",    "double",   "sum",  "#,##0.00 \"kr\""),
            ("line_revenue_nok",  "double",   "sum",  "#,##0.00 \"kr\""),
            ("line_cost_nok",     "double",   "sum",  "#,##0.00 \"kr\""),
            ("line_profit_nok",   "double",   "sum",  "#,##0.00 \"kr\""),
            ("line_margin_pct",   "double",   "average", "0.0%"),
        ],
        "hidden_columns": {"customer_sk", "product_sk", "order_date_key",
                           "customer_id", "product_id", "order_status"},
    },
}


# ────────────────────────────────────────────────────────────────────────────
# Relasjoner (star schema)
#   (from_table, from_col, to_table, to_col, cross_filtering_behavior)
# ────────────────────────────────────────────────────────────────────────────
RELATIONSHIPS = [
    # fct_order_items → dims
    ("fct_order_items", "customer_sk",    "dim_customer", "customer_sk",  "oneDirection"),
    ("fct_order_items", "product_sk",     "dim_product",  "product_sk",   "oneDirection"),
    ("fct_order_items", "order_date_key", "dim_date",     "date_key",     "oneDirection"),
    # fct_orders → dims
    ("fct_orders",      "customer_sk",    "dim_customer", "customer_sk",  "oneDirection"),
    ("fct_orders",      "order_date_key", "dim_date",     "date_key",     "oneDirection"),
]


# ────────────────────────────────────────────────────────────────────────────
# DAX-mål (table_name, measure_name, expression, format_string, display_folder)
# ────────────────────────────────────────────────────────────────────────────
MEASURES = [
    # ─── Volum (fct_order_items) ─────────────────────────────────────────────
    ("fct_order_items", "Antall ordrelinjer",
        "COUNTROWS('fct_order_items')",
        "#,##0", "1 · Volum"),

    ("fct_order_items", "Antall ordrer",
        "DISTINCTCOUNT('fct_order_items'[order_id])",
        "#,##0", "1 · Volum"),

    ("fct_order_items", "Antall kunder",
        "DISTINCTCOUNT('fct_order_items'[customer_id])",
        "#,##0", "1 · Volum"),

    ("fct_order_items", "Antall produkter solgt",
        "DISTINCTCOUNT('fct_order_items'[product_id])",
        "#,##0", "1 · Volum"),

    ("fct_order_items", "Antall enheter",
        "SUM('fct_order_items'[quantity])",
        "#,##0", "1 · Volum"),

    # ─── Revenue / Profit (1) ───────────────────────────────────────────────
    ("fct_order_items", "Total omsetning",
        "CALCULATE(SUM('fct_order_items'[line_revenue_nok]), 'fct_order_items'[is_completed] = TRUE())",
        "#,##0 \"kr\"", "2 · Omsetning"),

    ("fct_order_items", "Total kostnad",
        "CALCULATE(SUM('fct_order_items'[line_cost_nok]), 'fct_order_items'[is_completed] = TRUE())",
        "#,##0 \"kr\"", "2 · Omsetning"),

    ("fct_order_items", "Total fortjeneste",
        "[Total omsetning] - [Total kostnad]",
        "#,##0 \"kr\"", "2 · Omsetning"),

    ("fct_order_items", "Bruttomargin %",
        "DIVIDE([Total fortjeneste], [Total omsetning], 0)",
        "0.0%", "2 · Omsetning"),

    ("fct_order_items", "Returnert omsetning",
        "CALCULATE(SUM('fct_order_items'[line_revenue_nok]), 'fct_order_items'[order_status] = \"returned\")",
        "#,##0 \"kr\"", "2 · Omsetning"),

    ("fct_order_items", "Returandel %",
        "DIVIDE([Returnert omsetning], [Total omsetning] + [Returnert omsetning], 0)",
        "0.0%", "2 · Omsetning"),

    # ─── Kunde-KPI ──────────────────────────────────────────────────────────
    ("fct_order_items", "Snitt ordreverdi (AOV)",
        "DIVIDE([Total omsetning], [Antall ordrer], 0)",
        "#,##0 \"kr\"", "3 · Kunde"),

    ("fct_order_items", "Ordrer per kunde",
        "DIVIDE([Antall ordrer], [Antall kunder], 0)",
        "#,##0.0", "3 · Kunde"),

    ("fct_order_items", "Customer Lifetime Value",
        "DIVIDE([Total omsetning], [Antall kunder], 0)",
        "#,##0 \"kr\"", "3 · Kunde"),

    ("fct_order_items", "Linjer per ordre",
        "DIVIDE([Antall ordrelinjer], [Antall ordrer], 0)",
        "#,##0.0", "3 · Kunde"),

    # ─── Produkt-KPI ────────────────────────────────────────────────────────
    ("fct_order_items", "Snittpris per enhet",
        "DIVIDE([Total omsetning], [Antall enheter], 0)",
        "#,##0.00 \"kr\"", "4 · Produkt"),

    ("fct_order_items", "Fortjeneste per enhet",
        "DIVIDE([Total fortjeneste], [Antall enheter], 0)",
        "#,##0.00 \"kr\"", "4 · Produkt"),

    ("fct_order_items", "Andel av omsetning",
        "DIVIDE([Total omsetning], CALCULATE([Total omsetning], ALL('dim_product')), 0)",
        "0.0%", "4 · Produkt"),

    # ─── Tidsintelligens (på dim_date) ───────────────────────────────────────
    ("fct_order_items", "Omsetning hittil i år (YTD)",
        "TOTALYTD([Total omsetning], 'dim_date'[date])",
        "#,##0 \"kr\"", "5 · Tidsintelligens"),

    ("fct_order_items", "Omsetning hittil i mnd (MTD)",
        "TOTALMTD([Total omsetning], 'dim_date'[date])",
        "#,##0 \"kr\"", "5 · Tidsintelligens"),

    ("fct_order_items", "Omsetning forrige år",
        "CALCULATE([Total omsetning], SAMEPERIODLASTYEAR('dim_date'[date]))",
        "#,##0 \"kr\"", "5 · Tidsintelligens"),

    ("fct_order_items", "Omsetning forrige måned",
        "CALCULATE([Total omsetning], DATEADD('dim_date'[date], -1, MONTH))",
        "#,##0 \"kr\"", "5 · Tidsintelligens"),

    ("fct_order_items", "Vekst MoM %",
        "DIVIDE([Total omsetning] - [Omsetning forrige måned], [Omsetning forrige måned], 0)",
        "0.0%;-0.0%;0.0%", "5 · Tidsintelligens"),

    ("fct_order_items", "Vekst YoY %",
        "DIVIDE([Total omsetning] - [Omsetning forrige år], [Omsetning forrige år], 0)",
        "0.0%;-0.0%;0.0%", "5 · Tidsintelligens"),

    ("fct_order_items", "Rullerende 3 mnd omsetning",
        "CALCULATE([Total omsetning], DATESINPERIOD('dim_date'[date], LASTDATE('dim_date'[date]), -3, MONTH))",
        "#,##0 \"kr\"", "5 · Tidsintelligens"),

    # ─── Rangering / topp-N ─────────────────────────────────────────────────
    ("fct_order_items", "Topp-kunde omsetning",
        "MAXX(VALUES('dim_customer'[full_name]), [Total omsetning])",
        "#,##0 \"kr\"", "6 · Rangering"),

    ("fct_order_items", "Rangering kunde (oms)",
        "RANKX(ALL('dim_customer'[full_name]), [Total omsetning], , DESC, DENSE)",
        "0", "6 · Rangering"),

    ("fct_order_items", "Rangering produkt (oms)",
        "RANKX(ALL('dim_product'[product_name]), [Total omsetning], , DESC, DENSE)",
        "0", "6 · Rangering"),

    # ─── På fct_orders (ordrenivå-mål) ──────────────────────────────────────
    ("fct_orders", "Antall ordrer (header)",
        "DISTINCTCOUNT('fct_orders'[order_id])",
        "#,##0", "Header"),

    ("fct_orders", "Andel fullførte ordrer",
        "DIVIDE(\n"
        "    CALCULATE([Antall ordrer (header)], 'fct_orders'[is_completed] = TRUE()),\n"
        "    [Antall ordrer (header)],\n"
        "    0\n"
        ")",
        "0.0%", "Header"),
]


# ────────────────────────────────────────────────────────────────────────────
# TMDL-generering
# ────────────────────────────────────────────────────────────────────────────

DATA_TYPE_PBI = {
    "int64":    "int64",
    "double":   "double",
    "string":   "string",
    "dateTime": "dateTime",
    "boolean":  "boolean",
}


def tmdl_column(name, dtype, summarize_by, format_string,
                is_hidden=False, sort_by_column=None,
                data_category=None):
    lines = [f"\tcolumn {name}"]
    lines.append(f"\t\tdataType: {DATA_TYPE_PBI[dtype]}")
    if format_string:
        lines.append(f"\t\tformatString: {format_string}")
    lines.append(f"\t\tlineageTag: {lineage_guid()}")
    lines.append(f"\t\tsummarizeBy: {summarize_by}")
    lines.append(f"\t\tsourceColumn: {name}")
    if is_hidden:
        lines.append("\t\tisHidden")
    if sort_by_column:
        lines.append(f"\t\tsortByColumn: {sort_by_column}")
    if data_category:
        lines.append(f"\t\tdataCategory: {data_category}")
    lines.append("")
    lines.append("\t\tannotation SummarizationSetBy = Automatic")
    if dtype == "dateTime":
        lines.append("")
        lines.append("\t\tannotation UnderlyingDateTimeDataType = Date")
    return "\n".join(lines)


def tmdl_measure(name, expression, format_string, display_folder):
    """Render a TMDL measure block. Multi-line DAX is supported."""
    if "\n" in expression:
        # Multi-line DAX: use ``` fenced block
        expr = "```\n\t\t\t" + expression.replace("\n", "\n\t\t\t") + "\n\t\t\t```"
        head = f"\tmeasure '{name}' =\n\t\t{expr}"
    else:
        head = f"\tmeasure '{name}' = {expression}"
    parts = [head]
    if format_string:
        parts.append(f"\t\tformatString: {json.dumps(format_string)}")
    parts.append(f"\t\tlineageTag: {lineage_guid()}")
    if display_folder:
        parts.append(f"\t\tdisplayFolder: {display_folder}")
    parts.append("")
    parts.append("\t\tannotation PBI_FormatHint = {\"isGeneralNumber\":true}")
    return "\n".join(parts)


def tmdl_partition_csv(table_name, csv_filename):
    """
    Power Query M som leser en CSV-fil fra repo-mappen via parameter `RepoPath`.
    Mode = import.
    """
    m = (
        "let\n"
        f"\tSource = Csv.Document(\n"
        f"\t\tFile.Contents(RepoPath & \"/{csv_filename}\"),\n"
        "\t\t[Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),\n"
        "\tPromoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),\n"
        f"\tTyped = {table_name}_Types(Promoted)\n"
        "in\n"
        "\tTyped"
    )
    expr = "```\n\t\t\t" + m.replace("\n", "\n\t\t\t") + "\n\t\t\t```"
    return (
        f"\tpartition {table_name} = m\n"
        f"\t\tmode: import\n"
        f"\t\tsource =\n"
        f"\t\t\t{expr}"
    )


def build_csv_partition_simple(table_name, csv_filename, columns):
    """
    Selvstendig M-uttrykk som ikke trenger en separat type-funksjon.
    Bygger en Table.TransformColumnTypes-liste fra column-spec.
    """
    type_map = {
        "int64":    "Int64.Type",
        "double":   "type number",
        "string":   "type text",
        "dateTime": "type date",
        "boolean":  "type logical",
    }
    transform_pairs = []
    for col in columns:
        name, dtype = col[0], col[1]
        transform_pairs.append(f'{{"{name}", {type_map[dtype]}}}')
    transform_list = ", ".join(transform_pairs)

    m = (
        "let\n"
        f'\tSource = Csv.Document(File.Contents(RepoPath & "/{csv_filename}"),'
        f' [Delimiter=",", Columns={len(columns)}, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),\n'
        "\tPromoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),\n"
        f"\tTyped = Table.TransformColumnTypes(Promoted, {{{transform_list}}})\n"
        "in\n"
        "\tTyped"
    )
    return m


def render_table_tmdl(table_name, spec):
    cols = spec["columns"]
    hidden = spec.get("hidden_columns", set())
    sort_map = spec.get("sort_columns", {})
    data_category = spec.get("data_category")
    is_date_table = spec.get("is_date_table", False)

    out = [f"table {table_name}"]
    out.append(f"\tlineageTag: {lineage_guid()}")
    if is_date_table:
        out.append("\tdataCategory: Time")
    out.append("")

    for col in cols:
        name, dtype, summarize, fmt = col
        col_block = tmdl_column(
            name, dtype, summarize, fmt,
            is_hidden=(name in hidden),
            sort_by_column=sort_map.get(name),
            data_category="Time" if (is_date_table and name == "date") else None,
        )
        out.append(col_block)
        out.append("")

    # Measures
    for m_table, m_name, m_expr, m_fmt, m_folder in MEASURES:
        if m_table != table_name:
            continue
        out.append(tmdl_measure(m_name, m_expr, m_fmt, m_folder))
        out.append("")

    # Partition
    m_expr = build_csv_partition_simple(table_name, f"{table_name}.csv", cols)
    fenced = "```\n\t\t\t" + m_expr.replace("\n", "\n\t\t\t") + "\n\t\t\t```"
    out.append(f"\tpartition {table_name} = m")
    out.append("\t\tmode: import")
    out.append("\t\tsource =")
    out.append(f"\t\t\t{fenced}")
    out.append("")
    out.append("\tannotation PBI_ResultType = Table")
    return "\n".join(out) + "\n"


# ────────────────────────────────────────────────────────────────────────────
# Bygg dataset
# ────────────────────────────────────────────────────────────────────────────

def build_dataset():
    # .platform
    write_text(os.path.join(DATASET_DIR, ".platform"), json.dumps({
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/gitIntegration/platformProperties/2.0.0/schema.json",
        "metadata": {"type": "SemanticModel", "displayName": PROJECT_NAME},
        "config": {"version": "2.0", "logicalId": lineage_guid()}
    }, indent=2))

    def_dir = os.path.join(DATASET_DIR, "definition")

    # database.tmdl
    qorder = '","'.join(TABLES.keys())
    write_text(os.path.join(def_dir, "database.tmdl"),
        f"database {PROJECT_NAME}\n"
        f"\tcompatibilityLevel: 1567\n\n"
        f'\tannotation PBI_QueryOrder = ["{qorder}"]\n\n'
        f"\tannotation __PBI_TimeIntelligenceEnabled = 0\n"
    )

    # Generate stable relationship IDs so rebuilds don't churn lineageTags
    # Stable by hashing the (from, to) column pair.
    import hashlib
    rel_ids = []
    rel_lines = []
    for rel in RELATIONSHIPS:
        from_t, from_c, to_t, to_c, behaviour = rel
        sig = f"{from_t}.{from_c}=>{to_t}.{to_c}"
        h = hashlib.md5(sig.encode()).hexdigest()
        rid = f"{h[0:8]}-{h[8:12]}-{h[12:16]}-{h[16:20]}-{h[20:32]}"
        rel_ids.append(rid)
        rel_lines.append(f"relationship {rid}")
        rel_lines.append(f"\tfromColumn: {from_t}.{from_c}")
        rel_lines.append(f"\ttoColumn: {to_t}.{to_c}")
        if behaviour == "bothDirections":
            rel_lines.append("\tcrossFilteringBehavior: bothDirections")
        rel_lines.append("")

    # Put authoritative relationship blocks in relationships.tmdl
    write_text(os.path.join(def_dir, "relationships.tmdl"), "\n".join(rel_lines))

    # model.tmdl: refs only — ref table, ref cultureInfo, ref relationship
    table_refs = "\n".join(f"ref table {t}" for t in TABLES.keys())
    rel_refs = "\n".join(f"ref relationship {rid}" for rid in rel_ids)

    model_tmdl = (
        f"model Model\n"
        f"\tculture: nb-NO\n"
        f"\tdefaultPowerBIDataSourceVersion: powerBI_V3\n"
        f"\tsourceQueryCulture: nb-NO\n"
        f"\tdataAccessOptions\n"
        f"\t\tlegacyRedirects\n"
        f"\t\treturnErrorValuesAsNull\n"
        f"\n"
        f"\tannotation PBIDesktopVersion = 2.131.1203.0 (24.12)\n"
        f'\tannotation PBI_QueryOrder = ["{qorder}"]\n'
        f"\n"
        f"{table_refs}\n"
        f"\n"
        f"ref cultureInfo nb-NO\n"
        f"\n"
        f"{rel_refs}\n"
    )
    write_text(os.path.join(def_dir, "model.tmdl"), model_tmdl)

    # expressions.tmdl — RepoPath parameter
    expressions = (
        "expression RepoPath = \"" + DEFAULT_CSV_FOLDER + "\" meta [IsParameterQuery=true, "
        "Type=\"Text\", IsParameterQueryRequired=true]\n"
        "\tlineageTag: " + lineage_guid() + "\n"
        "\tqueryGroup: Parameters\n"
        "\n"
        "\tannotation PBI_ResultType = Text\n"
    )
    write_text(os.path.join(def_dir, "expressions.tmdl"), expressions)

    # culture.tmdl
    write_text(os.path.join(def_dir, "cultures", "nb-NO.tmdl"),
        "cultureInfo nb-NO\n"
    )

    # tables
    for table_name, spec in TABLES.items():
        path = os.path.join(def_dir, "tables", f"{table_name}.tmdl")
        write_text(path, render_table_tmdl(table_name, spec))

    # definition.pbism — semantic model entry point (modern PBIP)
    write_json(os.path.join(DATASET_DIR, "definition.pbism"), {
        "version": "1.0",
        "settings": {}
    })


# ────────────────────────────────────────────────────────────────────────────
# Bygg rapport
# ────────────────────────────────────────────────────────────────────────────

def base_visual(visual_type, x, y, width, height, title=None,
                z=1000, title_size="14pt", title_align="left"):
    v = {
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainer/2.6.0/schema.json",
        "name": gid(),
        "position": {"x": x, "y": y, "z": z,
                     "width": width, "height": height, "tabOrder": z},
        "visual": {
            "visualType": visual_type,
            "visualContainerObjects": {
                "border": [{"properties": {"show": {"expr": {"Literal": {"Value": "false"}}}}}],
                "background": [{"properties": {
                    "color": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{WHITE}'"}}}}},
                    "show": {"expr": {"Literal": {"Value": "true"}}},
                    "transparency": {"expr": {"Literal": {"Value": "0D"}}}
                }}],
            },
        },
    }
    if title:
        # Keep title styling minimal — let the theme drive colour/font.
        v["visual"]["visualContainerObjects"]["title"] = [{
            "properties": {
                "show": {"expr": {"Literal": {"Value": "true"}}},
                "text": {"expr": {"Literal": {"Value": f"'{title}'"}}}
            }
        }]
    else:
        v["visual"]["visualContainerObjects"]["title"] = [{
            "properties": {"show": {"expr": {"Literal": {"Value": "false"}}}}
        }]
    return v


def proj(table, col_or_measure, is_measure=False, active=False):
    if is_measure:
        field = {"Measure": {
            "Expression": {"SourceRef": {"Entity": table}},
            "Property": col_or_measure
        }}
    else:
        field = {"Column": {
            "Expression": {"SourceRef": {"Entity": table}},
            "Property": col_or_measure
        }}
    p = {"field": field,
         "queryRef": f"{table}.{col_or_measure}",
         "nativeQueryRef": col_or_measure}
    if active:
        p["active"] = True
    return p


def card(table, measure, x, y, w, h, title=None):
    v = base_visual("card", x, y, w, h, title)
    v["visual"]["query"] = {"queryState": {
        "Values": {"projections": [proj(table, measure, is_measure=True, active=True)]}
    }}
    return v


def column_chart(cat_table, cat_col, m_table, m_name, x, y, w, h, title=None):
    v = base_visual("columnChart", x, y, w, h, title)
    v["visual"]["query"] = {"queryState": {
        "Category": {"projections": [proj(cat_table, cat_col)]},
        "Y": {"projections": [proj(m_table, m_name, is_measure=True, active=True)]}
    }}
    return v


def bar_chart(cat_table, cat_col, m_table, m_name, x, y, w, h, title=None):
    v = base_visual("barChart", x, y, w, h, title)
    v["visual"]["query"] = {"queryState": {
        "Category": {"projections": [proj(cat_table, cat_col)]},
        "Y": {"projections": [proj(m_table, m_name, is_measure=True, active=True)]}
    }}
    return v


def line_chart(cat_table, cat_col, m_table, m_name, x, y, w, h, title=None):
    v = base_visual("lineChart", x, y, w, h, title)
    v["visual"]["query"] = {"queryState": {
        "Category": {"projections": [proj(cat_table, cat_col)]},
        "Y": {"projections": [proj(m_table, m_name, is_measure=True, active=True)]}
    }}
    return v


def donut_chart(cat_table, cat_col, m_table, m_name, x, y, w, h, title=None):
    v = base_visual("donutChart", x, y, w, h, title)
    v["visual"]["query"] = {"queryState": {
        "Category": {"projections": [proj(cat_table, cat_col)]},
        "Y": {"projections": [proj(m_table, m_name, is_measure=True, active=True)]}
    }}
    return v


def table_visual(table, columns, x, y, w, h, title=None, measures=None):
    """columns: list of plain column names. measures: list of (table, measure_name) tuples."""
    v = base_visual("tableEx", x, y, w, h, title)
    projections = [proj(table, c) for c in columns]
    for m in (measures or []):
        projections.append(proj(m[0], m[1], is_measure=True, active=True))
    v["visual"]["query"] = {"queryState": {
        "Values": {"projections": projections}
    }}
    return v


def slicer(table, column, x, y, w, h, title=None):
    v = base_visual("slicer", x, y, w, h, title)
    v["visual"]["query"] = {"queryState": {
        "Values": {"projections": [proj(table, column)]}
    }}
    return v


def shape(fill_color, x, y, w, h, z=500):
    return {
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainer/2.6.0/schema.json",
        "name": gid(),
        "position": {"x": x, "y": y, "z": z, "width": w, "height": h, "tabOrder": z},
        "visual": {
            "visualType": "shape",
            "objects": {
                "shape": [{"properties": {
                    "tileShape": {"expr": {"Literal": {"Value": "'rectangle'"}}}
                }}],
                "rotation": [{"properties": {
                    "shapeAngle": {"expr": {"Literal": {"Value": "0L"}}}
                }}],
                "fill": [{"properties": {
                    "fillColor": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{fill_color}'"}}}}},
                    "transparency": {"expr": {"Literal": {"Value": "0D"}}}
                }, "selector": {"id": "default"}}],
                "outline": [{"properties": {
                    "show": {"expr": {"Literal": {"Value": "false"}}}
                }}]
            },
            "drillFilterOtherVisuals": True
        }
    }


def textbox(text, x, y, w, h, font_size="11pt", weight="normal",
            color="#FFFFFF", z=1500, family="Segoe UI"):
    return {
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainer/2.6.0/schema.json",
        "name": gid(),
        "position": {"x": x, "y": y, "z": z, "width": w, "height": h, "tabOrder": z},
        "visual": {
            "visualType": "textbox",
            "objects": {"general": [{"properties": {"paragraphs": [{
                "textRuns": [{"value": text, "textStyle": {
                    "fontFamily": family,
                    "fontSize": font_size,
                    "fontWeight": weight,
                    "color": color
                }}]
            }]}}]}
        }
    }


def write_visual(page_name, v):
    path = os.path.join(REPORT_DIR, "definition", "pages", page_name,
                        "visuals", v["name"], "visual.json")
    write_json(path, v)
    BUILT_VISUALS.setdefault(page_name, set()).add(v["name"])


def neutralize_stale_visuals():
    """
    On mounted folders we can WRITE but not DELETE files. So for any visual.json
    left over from a previous build (random folder name we did not just generate),
    overwrite it with a 1×1 off-canvas hidden shape so Power BI ignores it.
    """
    pages_dir = os.path.join(REPORT_DIR, "definition", "pages")
    if not os.path.isdir(pages_dir):
        return
    for page in os.listdir(pages_dir):
        visuals_dir = os.path.join(pages_dir, page, "visuals")
        if not os.path.isdir(visuals_dir):
            continue
        live = BUILT_VISUALS.get(page, set())
        for folder in os.listdir(visuals_dir):
            if folder in live:
                continue
            stale_path = os.path.join(visuals_dir, folder, "visual.json")
            if not os.path.isfile(stale_path):
                continue
            # Overwrite with a 1px hidden shape off the canvas
            noop = {
                "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainer/2.6.0/schema.json",
                "name": folder,
                "position": {"x": -10000, "y": -10000, "z": 0,
                             "width": 1, "height": 1, "tabOrder": 0},
                "visual": {
                    "visualType": "shape",
                    "isHidden": True,
                    "objects": {
                        "shape": [{"properties": {
                            "tileShape": {"expr": {"Literal": {"Value": "'rectangle'"}}}
                        }}],
                        "fill": [{"properties": {
                            "fillColor": {"solid": {"color": {"expr": {"Literal": {"Value": "'#FFFFFF'"}}}}},
                            "transparency": {"expr": {"Literal": {"Value": "100D"}}}
                        }, "selector": {"id": "default"}}],
                        "outline": [{"properties": {
                            "show": {"expr": {"Literal": {"Value": "false"}}}
                        }}]
                    },
                    "drillFilterOtherVisuals": True
                }
            }
            try:
                with open(stale_path, "w", encoding="utf-8") as f:
                    json.dump(noop, f)
            except OSError:
                pass


def write_page(section_name, display_name, ordinal):
    set_current_page(section_name)
    path = os.path.join(REPORT_DIR, "definition", "pages", section_name)
    write_json(os.path.join(path, "page.json"), {
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/2.1.0/schema.json",
        "name": section_name,
        "displayName": display_name,
        "displayOption": "FitToPage",
        "width": CANVAS_W,
        "height": CANVAS_H,
        "ordinal": ordinal,
        "objects": {
            "background": [{"properties": {
                "color": {"solid": {"color": {"expr": {"Literal": {"Value": f"'{BRAND_BG}'"}}}}},
                "transparency": {"expr": {"Literal": {"Value": "0D"}}}
            }}]
        }
    })
    os.makedirs(os.path.join(path, "visuals"), exist_ok=True)


# ────────────────────────────────────────────────────────────────────────────
# Sidedesign — felles header
# ────────────────────────────────────────────────────────────────────────────

def render_header(page, title, subtitle=""):
    # Top navy band
    write_visual(page, shape(BRAND_NAVY, 0, 0, CANVAS_W, 110, z=100))
    # Accent stripe
    write_visual(page, shape(BRAND_TEAL, 0, 110, CANVAS_W, 6, z=110))
    # Title
    write_visual(page, textbox(title, 40, 20, 1400, 50,
                               font_size="28pt", weight="bold", color=WHITE, z=120))
    if subtitle:
        write_visual(page, textbox(subtitle, 40, 70, 1400, 30,
                                   font_size="12pt", color="#D8E1EA", z=121))
    # Brand mark right-aligned
    write_visual(page, textbox("GRITERA · ANALYTICS", CANVAS_W - 380, 40, 340, 30,
                               font_size="11pt", weight="bold", color=BRAND_GOLD,
                               z=122))


def render_footer(page, page_label):
    write_visual(page, shape("#E8ECF1", 0, CANVAS_H - 30, CANVAS_W, 30, z=100))
    write_visual(page, textbox(
        f"SalesAnalytics · GenAI-generert demo · {page_label}",
        20, CANVAS_H - 26, 1880, 22,
        font_size="9pt", color=BRAND_GREY, z=120))


# ────────────────────────────────────────────────────────────────────────────
# Page 1 — Executive dashboard
# ────────────────────────────────────────────────────────────────────────────

def build_page_executive():
    page = "ReportSection1"
    write_page(page, "Executive", 0)
    render_header(page, "Executive Dashboard",
                  "Topp-linje-KPIer for salg, kunde og produkt")

    # KPI-rad (4 kort)
    write_visual(page, card("fct_order_items", "Total omsetning",
                            40, 140, 440, 160, "Total omsetning"))
    write_visual(page, card("fct_order_items", "Total fortjeneste",
                            500, 140, 440, 160, "Total fortjeneste"))
    write_visual(page, card("fct_order_items", "Antall ordrer",
                            960, 140, 440, 160, "Antall ordrer"))
    write_visual(page, card("fct_order_items", "Antall kunder",
                            1420, 140, 460, 160, "Antall kunder"))

    # KPI-rad 2 (3 kort)
    write_visual(page, card("fct_order_items", "Snitt ordreverdi (AOV)",
                            40, 320, 590, 150, "Snitt ordreverdi (AOV)"))
    write_visual(page, card("fct_order_items", "Customer Lifetime Value",
                            650, 320, 590, 150, "Customer Lifetime Value"))
    write_visual(page, card("fct_order_items", "Bruttomargin %",
                            1260, 320, 620, 150, "Bruttomargin %"))

    # Stor trendgraf (måned)
    write_visual(page, line_chart(
        "dim_date", "year_month",
        "fct_order_items", "Total omsetning",
        40, 490, 1200, 420,
        title="Omsetningstrend per måned"))

    # Kategori-donut
    write_visual(page, donut_chart(
        "dim_product", "category",
        "fct_order_items", "Total omsetning",
        1260, 490, 620, 420,
        title="Omsetning per kategori"))

    # Slicer-rad
    write_visual(page, slicer("dim_date", "year", 40, 930, 280, 110, "År"))
    write_visual(page, slicer("dim_product", "category", 340, 930, 320, 110, "Kategori"))
    write_visual(page, slicer("dim_customer", "region", 680, 930, 280, 110, "Region"))

    render_footer(page, "Side 1 av 6 · Executive")


# ────────────────────────────────────────────────────────────────────────────
# Page 2 — Sales overview
# ────────────────────────────────────────────────────────────────────────────

def build_page_sales():
    page = "ReportSection2"
    write_page(page, "Salg", 1)
    render_header(page, "Salgsoversikt",
                  "Detaljert salgsanalyse — geografi, status og månedstrend")

    # KPI-rad
    write_visual(page, card("fct_order_items", "Total omsetning",
                            40, 140, 440, 150, "Omsetning"))
    write_visual(page, card("fct_order_items", "Antall ordrer",
                            500, 140, 440, 150, "Ordrer"))
    write_visual(page, card("fct_order_items", "Antall enheter",
                            960, 140, 440, 150, "Enheter solgt"))
    write_visual(page, card("fct_order_items", "Snitt ordreverdi (AOV)",
                            1420, 140, 460, 150, "AOV"))

    # Bar chart: omsetning per region
    write_visual(page, bar_chart(
        "dim_customer", "region",
        "fct_order_items", "Total omsetning",
        40, 310, 920, 400,
        title="Omsetning per region"))

    # Donut: ordrer per status
    write_visual(page, donut_chart(
        "fct_orders", "order_status_no",
        "fct_orders", "Antall ordrer (header)",
        980, 310, 900, 400,
        title="Ordrer per status"))

    # Tabell: kategori-prestasjon
    write_visual(page, table_visual(
        "dim_product", ["category"],
        40, 730, 920, 310,
        title="Omsetning og fortjeneste per kategori",
        measures=[
            ("fct_order_items", "Total omsetning"),
            ("fct_order_items", "Total fortjeneste"),
            ("fct_order_items", "Bruttomargin %"),
        ]))

    # Line chart: ordrer over tid
    write_visual(page, line_chart(
        "dim_date", "year_month",
        "fct_order_items", "Antall ordrer",
        980, 730, 900, 310,
        title="Antall ordrer per måned"))

    render_footer(page, "Side 2 av 6 · Salg")


# ────────────────────────────────────────────────────────────────────────────
# Page 3 — Customer insights
# ────────────────────────────────────────────────────────────────────────────

def build_page_customers():
    page = "ReportSection3"
    write_page(page, "Kunder", 2)
    render_header(page, "Kunde-innsikt",
                  "Lojalitet, region, kohorter og topp-kunder")

    # KPI-rad
    write_visual(page, card("fct_order_items", "Antall kunder",
                            40, 140, 440, 150, "Aktive kunder"))
    write_visual(page, card("fct_order_items", "Ordrer per kunde",
                            500, 140, 440, 150, "Ordrer per kunde"))
    write_visual(page, card("fct_order_items", "Customer Lifetime Value",
                            960, 140, 440, 150, "CLV"))
    write_visual(page, card("fct_order_items", "Snitt ordreverdi (AOV)",
                            1420, 140, 460, 150, "AOV"))

    # Bar: omsetning per region
    write_visual(page, bar_chart(
        "dim_customer", "region",
        "fct_order_items", "Total omsetning",
        40, 310, 600, 400,
        title="Omsetning per region"))

    # Bar: omsetning per tenure_segment
    write_visual(page, column_chart(
        "dim_customer", "tenure_segment",
        "fct_order_items", "Total omsetning",
        660, 310, 600, 400,
        title="Omsetning per lojalitetssegment"))

    # Donut: customer status
    write_visual(page, donut_chart(
        "dim_customer", "customer_status",
        "fct_order_items", "Total omsetning",
        1280, 310, 600, 400,
        title="Omsetning per kundestatus"))

    # Topp-10 kunder
    write_visual(page, table_visual(
        "dim_customer", ["full_name", "region", "tenure_segment"],
        40, 730, 1840, 310,
        title="Topp kunder etter omsetning",
        measures=[
            ("fct_order_items", "Total omsetning"),
            ("fct_order_items", "Antall ordrer"),
            ("fct_order_items", "Snitt ordreverdi (AOV)"),
        ]))

    render_footer(page, "Side 3 av 6 · Kunder")


# ────────────────────────────────────────────────────────────────────────────
# Page 4 — Product performance
# ────────────────────────────────────────────────────────────────────────────

def build_page_products():
    page = "ReportSection4"
    write_page(page, "Produkt", 3)
    render_header(page, "Produkt-prestasjon",
                  "Mest solgte produkter, marginer og leverandører")

    # KPI-rad
    write_visual(page, card("fct_order_items", "Antall produkter solgt",
                            40, 140, 440, 150, "Produkter solgt"))
    write_visual(page, card("fct_order_items", "Antall enheter",
                            500, 140, 440, 150, "Enheter"))
    write_visual(page, card("fct_order_items", "Snittpris per enhet",
                            960, 140, 440, 150, "Snittpris"))
    write_visual(page, card("fct_order_items", "Fortjeneste per enhet",
                            1420, 140, 460, 150, "Fortjeneste/enhet"))

    # Bar: topp produkter omsetning
    write_visual(page, bar_chart(
        "dim_product", "product_name",
        "fct_order_items", "Total omsetning",
        40, 310, 920, 400,
        title="Topp produkter etter omsetning"))

    # Column: omsetning per kategori
    write_visual(page, column_chart(
        "dim_product", "category",
        "fct_order_items", "Total fortjeneste",
        980, 310, 460, 400,
        title="Fortjeneste per kategori"))

    # Donut: pristier
    write_visual(page, donut_chart(
        "dim_product", "price_tier",
        "fct_order_items", "Total omsetning",
        1460, 310, 420, 400,
        title="Omsetning per pristier"))

    # Tabell: produktprestasjon
    write_visual(page, table_visual(
        "dim_product",
        ["product_name", "category", "supplier", "list_margin_pct"],
        40, 730, 1840, 310,
        title="Produkt-rangering",
        measures=[
            ("fct_order_items", "Total omsetning"),
            ("fct_order_items", "Antall enheter"),
            ("fct_order_items", "Total fortjeneste"),
            ("fct_order_items", "Bruttomargin %"),
        ]))

    render_footer(page, "Side 4 av 6 · Produkt")


# ────────────────────────────────────────────────────────────────────────────
# Page 5 — Trend / Time intelligence
# ────────────────────────────────────────────────────────────────────────────

def build_page_trends():
    page = "ReportSection5"
    write_page(page, "Trender", 4)
    render_header(page, "Trender og tidsanalyse",
                  "YoY-vekst, hittil i år og rullerende trender")

    # KPI-rad
    write_visual(page, card("fct_order_items", "Total omsetning",
                            40, 140, 440, 150, "Omsetning"))
    write_visual(page, card("fct_order_items", "Omsetning hittil i år (YTD)",
                            500, 140, 440, 150, "YTD"))
    write_visual(page, card("fct_order_items", "Omsetning forrige år",
                            960, 140, 440, 150, "Fjorår"))
    write_visual(page, card("fct_order_items", "Vekst YoY %",
                            1420, 140, 460, 150, "YoY-vekst"))

    # Line: månedstrend mot fjorår
    write_visual(page, line_chart(
        "dim_date", "year_month",
        "fct_order_items", "Total omsetning",
        40, 310, 1840, 400,
        title="Månedlig omsetning (alle år)"))

    # Column: kvartals-omsetning
    write_visual(page, column_chart(
        "dim_date", "year_quarter",
        "fct_order_items", "Total omsetning",
        40, 730, 920, 310,
        title="Omsetning per kvartal"))

    # Column: vekst per måned
    write_visual(page, column_chart(
        "dim_date", "year_month",
        "fct_order_items", "Rullerende 3 mnd omsetning",
        980, 730, 900, 310,
        title="Rullerende 3 måneders omsetning"))

    render_footer(page, "Side 5 av 6 · Trender")


# ────────────────────────────────────────────────────────────────────────────
# Page 6 — Dokumentasjon
# ────────────────────────────────────────────────────────────────────────────

def build_page_documentation():
    page = "ReportSection6"
    write_page(page, "Dokumentasjon", 5)

    # Top navy band
    write_visual(page, shape(BRAND_NAVY, 0, 0, CANVAS_W, 110, z=100))
    write_visual(page, shape(BRAND_TEAL, 0, 110, CANVAS_W, 6, z=110))
    write_visual(page, textbox("Dokumentasjon", 40, 20, 1400, 50,
                               font_size="28pt", weight="bold", color=WHITE, z=120))
    write_visual(page, textbox("Datamodell, mål og forutsetninger",
                               40, 70, 1400, 30, font_size="12pt",
                               color="#D8E1EA", z=121))

    # Left sidebar with TOC
    write_visual(page, shape(BRAND_NAVY, 0, 116, 360, CANVAS_H - 116, z=90))
    write_visual(page, textbox("Innhold", 30, 150, 320, 40,
                               font_size="16pt", weight="bold", color=BRAND_GOLD))
    toc_items = [
        "01  Om rapporten",
        "02  Datakilder og modell",
        "03  Begreper og definisjoner",
        "04  Sidebeskrivelser",
        "05  Nøkkelmål (DAX)",
        "06  Kontakt og eierskap",
    ]
    for i, item in enumerate(toc_items):
        write_visual(page, textbox(item, 30, 210 + i * 40, 320, 30,
                                   font_size="12pt", color="#D8E1EA"))

    # Two columns of content
    col1_x = 400
    col2_x = 1160
    col_w = 720

    # 01 Om rapporten
    write_visual(page, textbox("01 · Om rapporten", col1_x, 140, col_w, 30,
                               font_size="14pt", weight="bold", color=BRAND_NAVY))
    write_visual(page, textbox(
        "SalesAnalytics gir innsikt i salg, kunder og produkter "
        "for kursdemoen. Modellen er bygd fra dimensjonelle marter "
        "i `models/marts/core/` (dbt) og leser CSV-eksport fra "
        "`powerbi/data/`.",
        col1_x, 175, col_w, 100,
        font_size="10pt", color=BRAND_GREY))

    # 02 Datakilder
    write_visual(page, textbox("02 · Datakilder og modell", col1_x, 290, col_w, 30,
                               font_size="14pt", weight="bold", color=BRAND_NAVY))
    write_visual(page, textbox(
        "Star schema med dim_customer, dim_product og dim_date som "
        "konformerte dimensjoner. Faktatabeller: fct_orders (ordre-grain) "
        "og fct_order_items (linje-grain). Relasjonene er 1-til-mange "
        "fra dim → fact og bruker surrogatnøkler.",
        col1_x, 325, col_w, 130,
        font_size="10pt", color=BRAND_GREY))

    # 03 Begreper
    write_visual(page, textbox("03 · Begreper og definisjoner",
                               col1_x, 470, col_w, 30,
                               font_size="14pt", weight="bold", color=BRAND_NAVY))
    write_visual(page, textbox(
        "Omsetning = SUM(line_revenue_nok) der is_completed = TRUE.\n"
        "Fortjeneste = Omsetning − Kostnad.\n"
        "AOV = Omsetning / Antall ordrer.\n"
        "CLV = Omsetning / Antall kunder (forenklet, ikke tidsdiskontert).\n"
        "Vekst YoY % = (Omsetning − Fjorår) / Fjorår.",
        col1_x, 505, col_w, 200,
        font_size="10pt", color=BRAND_GREY))

    # 04 Sidebeskrivelser
    write_visual(page, textbox("04 · Sidebeskrivelser", col2_x, 140, col_w, 30,
                               font_size="14pt", weight="bold", color=BRAND_NAVY))
    write_visual(page, textbox(
        "Executive  — KPI-er, månedstrend og kategoriandel.\n"
        "Salg          — region-, status- og månedsanalyse.\n"
        "Kunder        — lojalitet, kohorter, topp-kunder.\n"
        "Produkt       — produkt- og leverandørprestasjon.\n"
        "Trender       — YoY, YTD og rullerende vinduer.",
        col2_x, 175, col_w, 200,
        font_size="10pt", color=BRAND_GREY))

    # 05 Mål
    write_visual(page, textbox("05 · Nøkkelmål (DAX)", col2_x, 390, col_w, 30,
                               font_size="14pt", weight="bold", color=BRAND_NAVY))
    write_visual(page, textbox(
        f"Totalt {len(MEASURES)} mål, organisert i display-mapper: "
        f"Volum, Omsetning, Kunde, Produkt, Tidsintelligens, Rangering.\n\n"
        "Alle mål bruker DIVIDE() for trygg deling og CALCULATE() med "
        "is_completed-filter for å ekskludere returer og pending ordrer.",
        col2_x, 425, col_w, 200,
        font_size="10pt", color=BRAND_GREY))

    # 06 Kontakt
    write_visual(page, textbox("06 · Kontakt og eierskap", col2_x, 640, col_w, 30,
                               font_size="14pt", weight="bold", color=BRAND_NAVY))
    write_visual(page, textbox(
        "Eier: Analytics & GenAI-teamet, Gritera Advisory.\n"
        "Kildemodell: models/marts/core/ (dbt, DuckDB-mål).\n"
        "Generert av Claude — desember 2024.",
        col2_x, 675, col_w, 120,
        font_size="10pt", color=BRAND_GREY))

    render_footer(page, "Side 6 av 6 · Dokumentasjon")


# ────────────────────────────────────────────────────────────────────────────
# Rapport-fundament
# ────────────────────────────────────────────────────────────────────────────

def build_report():
    # .platform
    write_text(os.path.join(REPORT_DIR, ".platform"), json.dumps({
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/gitIntegration/platformProperties/2.0.0/schema.json",
        "metadata": {"type": "Report", "displayName": PROJECT_NAME},
        "config": {"version": "2.0", "logicalId": lineage_guid()}
    }, indent=2))

    # definition.pbir — report entry point linking to the semantic model
    write_json(os.path.join(REPORT_DIR, "definition.pbir"), {
        "version": "1.0",
        "datasetReference": {
            "byPath": {"path": f"../{PROJECT_NAME}.SemanticModel"}
        }
    })

    # report.json
    write_json(os.path.join(REPORT_DIR, "definition", "report.json"), {
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/report/3.7.0/schema.json",
        "themeCollection": {
            "customTheme": {
                "name": "GriteraAnalytics",
                "path": "GriteraAnalytics.json",
                "type": "RegisteredResources"
            }
        },
        "resourcePackages": [{
            "name": "SharedResources",
            "type": "SharedResources",
            "items": [
                {"name": "CY24SU10", "path": "BaseThemes/CY24SU10.json", "type": "BaseTheme"}
            ]
        }, {
            "name": "RegisteredResources",
            "type": "RegisteredResources",
            "items": [
                {"name": "GriteraAnalytics", "path": "GriteraAnalytics.json", "type": "RegisteredTheme"}
            ]
        }],
        "sections": [
            {"name": "ReportSection1"},
            {"name": "ReportSection2"},
            {"name": "ReportSection3"},
            {"name": "ReportSection4"},
            {"name": "ReportSection5"},
            {"name": "ReportSection6"},
        ],
        "settings": {"useEnhancedTooltips": True}
    })

    # Custom theme — Gritera Analytics
    write_json(os.path.join(REPORT_DIR, "StaticResources",
                            "RegisteredResources", "GriteraAnalytics.json"), {
        "name": "GriteraAnalytics",
        "dataColors": [
            BRAND_TEAL, BRAND_GOLD, BRAND_NAVY, "#7AB6BF",
            "#D77E5D", "#7C9EB2", "#9CCAD0", "#C5A052",
            "#4F6D8A", "#A8B5C0"
        ],
        "background": BRAND_BG,
        "foreground": BRAND_NAVY,
        "tableAccent": BRAND_TEAL,
        "good":    "#4FB286",
        "neutral": "#E0A458",
        "bad":     "#D9534F",
        "visualStyles": {
            "*": {
                "*": {
                    "title": [{
                        "fontColor": {"solid": {"color": BRAND_NAVY}},
                        "fontSize": 14,
                        "fontFamily": "Segoe UI Semibold"
                    }],
                    "background": [{
                        "color": {"solid": {"color": WHITE}},
                        "transparency": 0
                    }],
                    "border": [{
                        "show": True,
                        "color": {"solid": {"color": "#E5E9EF"}},
                        "radius": 4
                    }]
                }
            },
            "card": {
                "*": {
                    "labels": [{
                        "color": {"solid": {"color": BRAND_NAVY}},
                        "fontSize": 32,
                        "fontFamily": "Segoe UI Semibold"
                    }],
                    "categoryLabels": [{
                        "color": {"solid": {"color": BRAND_GREY}},
                        "fontSize": 11
                    }]
                }
            }
        }
    })

    # Pages
    build_page_executive()
    build_page_sales()
    build_page_customers()
    build_page_products()
    build_page_trends()
    build_page_documentation()


# ────────────────────────────────────────────────────────────────────────────
# Pbip entry-point
# ────────────────────────────────────────────────────────────────────────────

def build_pbip_entry():
    write_json(os.path.join(ROOT, f"{PROJECT_NAME}.pbip"), {
        "version": "1.0",
        "artifacts": [
            {"report": {"path": f"{PROJECT_NAME}.Report"}}
        ],
        "settings": {
            "enableAutoRecovery": True
        }
    })


# ────────────────────────────────────────────────────────────────────────────
# Main
# ────────────────────────────────────────────────────────────────────────────

def _rm_tree_safe(path):
    """Walk and delete files/dirs individually — robust on mounted folders."""
    if not os.path.isdir(path):
        return
    for root, dirs, files in os.walk(path, topdown=False):
        for f in files:
            try:
                os.remove(os.path.join(root, f))
            except OSError:
                pass
        for d in dirs:
            try:
                os.rmdir(os.path.join(root, d))
            except OSError:
                pass
    try:
        os.rmdir(path)
    except OSError:
        pass





def main():
    # Clean previous build artifacts (keep CSV data & build script intact)
    legacy_dataset = os.path.join(ROOT, f"{PROJECT_NAME}.Dataset")
    for d in (DATASET_DIR, REPORT_DIR, legacy_dataset):
        _rm_tree_safe(d)
    for f in os.listdir(ROOT):
        if f.endswith(".pbip"):
            try:
                os.remove(os.path.join(ROOT, f))
            except OSError:
                pass

    print(f"Building {PROJECT_NAME} ...")
    build_pbip_entry()
    build_dataset()
    build_report()
    neutralize_stale_visuals()
    print(f"Done. Open powerbi/{PROJECT_NAME}.pbip in Power BI Desktop.")
    print()
    print("Tip: open the model in Power BI Desktop and make sure the")
    print("'RepoPath' parameter points to the absolute path of powerbi/data.")


if __name__ == "__main__":
    main()
